-- 회원 테이블
CREATE TABLE "MEMBER" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"MEMBER_ID"	VARCHAR2(30)		NULL,
	"MEMBER_PW"	VARCHAR2(30)		NULL,
	"MEMBER_ROLE"	VARCHAR2(30)		NULL,
	"MEMBER_NAME"	VARCHAR2(30)		NULL,
	"MEMBER_EMAIL"	VARCHAR2(50)		NULL,
	"MEMBER_PHONE"	VARCHAR2(11)		NULL,
	"MEMBER_ED"	DATE		NULL,
	"MEMBER_MD"	DATE		NULL,
	"MEMBER_STATUS"	VARCHAR2(3)		NULL
);

COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_ID" IS '회원아이디';

COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '비밀번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_ROLE" IS '회원타입';

COMMENT ON COLUMN "MEMBER"."MEMBER_NAME" IS '이름';

COMMENT ON COLUMN "MEMBER"."MEMBER_EMAIL" IS '이메일';

COMMENT ON COLUMN "MEMBER"."MEMBER_PHONE" IS '전화번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_ED" IS '회원가입일';

COMMENT ON COLUMN "MEMBER"."MEMBER_MD" IS '회원수정일';

COMMENT ON COLUMN "MEMBER"."MEMBER_STATUS" IS '회원상태';

SELECT * FROM ALL_CONSTRAINTS
WHERE TABLE_NAME = 'MEMBER';

ALTER TABLE MEMBER DROP CONSTRAINT SYS_C008474;
ALTER TABLE MEMBER ADD CONSTRAINT MEMBER_NO_PK PRIMARY KEY (MEMBER_NO);
ALTER TABLE MEMBER MODIFY MEMBER_STATUS DEFAULT 'Y';
ALTER TABLE MEMBER MODIFY MEMBER_ROLE DEFAULT 'ROLE_USER';
ALTER TABLE MEMBER MODIFY MEMBER_ED DEFAULT SYSDATE;
ALTER TABLE MEMBER MODIFY MEMBER_MD DEFAULT SYSDATE;
ALTER TABLE MEMBER MODIFY MEMBER_PW VARCHAR2(300);

CREATE SEQUENCE SEQ_MEMBER_NO;

SELECT MEMBER_NO,
       MEMBER_ID,
       MEMBER_PW,
       MEMBER_ROLE,
       MEMBER_NAME,
       MEMBER_EMAIL,
       MEMBER_PHONE,
       MEMBER_ED,
       MEMBER_MD,
       MEMBER_STATUS
FROM MEMBER
WHERE MEMBER_ID = 'admin';

select *
from member
where LOWER(MEMBER_ID) = LOWER('test02');


INSERT INTO MEMBER
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'admin', '1234', 'ROLE_ADMIN', '관리자', 'NULL', 'NULL', SYSDATE, SYSDATE, 'Y');

INSERT INTO MEMBER
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'test04', '1234', 'ROLE_user', 'test04', 'NULL', 'NULL', SYSDATE, SYSDATE, 'Y');

INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_PHONE)
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'lee0101', 'hello1234', '이무기', '01012341234');

-- 숙소 테이블
DELETE FROM HOUSE;

ALTER TABLE HOUSE ADD CONSTRAINT H_CODE_PK PRIMARY KEY (H_CODE);

-- 지역코드 테이블
CREATE TABLE AREAINFO (
    AREA_CODE NUMBER,
    AREA_NAME VARCHAR2(30),
    SIGUNGU_CODE NUMBER,
    SIGUNGU_NAME VARCHAR2(30)
);

SELECT DISTINCT AREA_CODE,
       AREA_NAME
FROM AREAINFO;


COMMIT;

ROLLBACK;